services:
  spacerobot-container:
    build:
      context: .
      dockerfile: Dockerfile
      network: host
      args:
        LOCAL_UID: ${UID}
        LOCAL_GID: ${GID}
        USER_NAME: ${USER_NAME}
    runtime: nvidia
    env_file: .env
    image: ${USER_NAME}/${WORKSPACE_NAME}
    container_name: ${WORKSPACE_NAME}
    privileged: true
    user: "${UID}:${GID}"
    network_mode: host
    ipc: host
    shm_size: "1g"
    stop_grace_period: 1s
    environment:
      - DISPLAY=${DISPLAY}
      - PULSE_SERVER=unix:/run/user/${UID}/pulse/native
      - CONTAINER_NAME=${WORKSPACE_NAME}
    devices:
      - /dev/snd
    volumes:
      - ${XDG_RUNTIME_DIR}/pulse:/run/user/${UID}/pulse
      - ../src:/home/${USER_NAME}/colcon_ws/src
      - /etc/udev/rules.d/:/etc/udev/rules.d/
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    stdin_open: true
    tty: true
