services:
  spacerobot-container:
    build:
      context: .
      dockerfile: Dockerfile
      network: host
      args:
        ARCHITECTURE: ${ARCHITECTURE}
        LOCAL_UID: ${LOCAL_UID}
        LOCAL_GID: ${LOCAL_GID}
        USERNAME: ${USERNAME}
        CONTAINER_NAME: ${CONTAINER_NAME}
    runtime: nvidia
    env_file: .env
    image: ${USERNAME}/${CONTAINER_NAME}
    container_name: ${CONTAINER_NAME}
    privileged: true
    user: "${LOCAL_UID}:${LOCAL_GID}"
    network_mode: host
    ipc: host
    shm_size: "1g"
    stop_grace_period: 1s
    environment:
      - DISPLAY=${DISPLAY}
      - PULSE_SERVER=unix:/run/user/${LOCAL_UID}/pulse/native
    devices:
      - /dev/snd
    volumes:
      - ${XDG_RUNTIME_DIR}/pulse:/run/user/${LOCAL_UID}/pulse
      - ../src:/home/${USERNAME}/colcon_ws/src
      - /dev/bus/usb:/dev/bus/usb
      - /etc/udev/rules.d/:/etc/udev/rules.d/
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    stdin_open: true
    tty: true
